// Aseprite Document Library
// Copyright (c) 2019-present  Igara Studio S.A.
// Copyright (c) 2001-2018 David Capello
//
// This file is released under the terms of the MIT license.
// Read LICENSE.txt for more information.

#ifndef DOC_ALGORITHM_RESIZE_IMAGE_H_INCLUDED
#define DOC_ALGORITHM_RESIZE_IMAGE_H_INCLUDED
#pragma once

#include "doc/color.h"
#include "doc/image_buffer.h"
#include "gfx/fwd.h"

namespace doc {
class Image;
class Palette;
class RgbMap;

namespace algorithm {

enum ResizeMethod {
  RESIZE_METHOD_NEAREST_NEIGHBOR,
  RESIZE_METHOD_BILINEAR,
  RESIZE_METHOD_ROTSPRITE,
};

struct ResizeImage {
  ResizeMethod method = RESIZE_METHOD_NEAREST_NEIGHBOR;
  const Palette* palette = nullptr;
  const RgbMap* rgbMap = nullptr;

  // Useful only for indexed mode, generally it should be equal to
  // src->maskColor() but with -1 we can copy all indexes.
  color_t maskColor = -1;

  // True if the "src" image should be copied (to avoid modifications
  // by prepare/flattenTransparentPixels() functions).
  bool copySrc = false;

  // A temporal buffer to be re-used on each resize to create "src" copies
  // (only useful if copySrc = true).
  ImageBufferPtr srcTmpBuffer = nullptr;

  // Resizes the source image "src" to the destination image "dst".
  //
  // Warning: If you are using the method == RESIZE_METHOD_BILINEAR,
  // the "src" image will be first filtered with
  // prepare/flattenTransparentPixels() functions, which modifies the
  // transparent pixels of the "src" image. You can use "copySrc" to
  // avoid modifying the original "src" image at all.
  void operator()(Image* src, Image* dst) const;

private:
  // It does not modify the image to the human eye, but internally
  // tries to fixup all colors that are completely transparent (alpha
  // = 0) with the average of its 4-neighbors. Useful if you want to
  // use ResizeImage with images that contains transparent pixels.
  static void prepareTransparentPixels(Image* image);

  // Removes invisible pixels (alpha == 0 && RGB != 0) generated by
  // prepareTransparentPixels() converting then to RGBA=0.
  static void flattenTransparentPixels(Image* image);
};

} // namespace algorithm
} // namespace doc

#endif
